[package]
name = "ocp-ocl"
version = "0.1.0"
edition = "2021"

[lib]
name = "ocp_ocl"
path = "src/lib.rs"

[features]
default = []
w20_chaos = []

[dependencies]
sha2 = "0.10"

[workspace]
members = [
    ".",
    "xtask",
    "projects/ocp-ocl/crates/ocl-runtime-core",
    "projects/ocp-ocl/crates/ocl-sdk",
    "projects/ocp-ocl/crates/ocl-cli",
]
resolver = "2"

[dev-dependencies]
ocl-sdk = { path = "projects/ocp-ocl/crates/ocl-sdk" }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
