[package]
name = "ocp"
version = "0.1.0"
edition = "2021"
authors = ["DucHaiten"]
license = "AGPL-3.0-only"

[lib]
name = "ocp"
path = "src/lib.rs"

[features]
default = []
w20_chaos = []

[dependencies]
sha2 = "0.10"

[workspace]
members = [
    ".",
    "xtask",
    "projects/ocp/crates/ocp-runtime-core",
    "projects/ocp/crates/ocp-sdk",
    "projects/ocp/crates/ocp-cli",
    "projects/ocp/crates/ocp-lsp",
    "projects/ocp/crates/ocp-dap",
]
resolver = "2"

[dev-dependencies]
ocp-sdk = { path = "projects/ocp/crates/ocp-sdk" }
ocp-runtime-core = { path = "projects/ocp/crates/ocp-runtime-core" }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
