[package]
name = "ocp-cli"
version = "0.1.0"
edition = "2021"
authors = ["DucHaiten"]
license = "AGPL-3.0-only"
default-run = "ocp"

[dependencies]
ocp-sdk = { path = "../ocp-sdk" }
ocp-runtime-core = { path = "../ocp-runtime-core" }
sha2 = "0.10"
serde_json = "1"

[[bin]]
name = "ocp"
path = "src/main.rs"
