[package]
name = "composer_demo"
version = "0.1.0"

[targets]
default = "main"

[dependencies]
std = "0.1.0"

[permissions.package]
allow = ["*"]
deny = ["std.net.poll"]

[permissions.std_fs]
read = ["./**"]
list = ["./**"]
write = ["./src/generated/**"]
